on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.18.x, 1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: go test ./...
      - name: Update Coverage
        uses: ncruces/go-coverage-report@main
        if: |
          matrix.os == 'ubuntu-latest' &&
          matrix.go-version == '1.20.x' &&
          github.event_name == 'push'
        continue-on-error: true
